enketo-core: fix getter-only number-input properties (#1367)
Before this fix, the browser console in strict mode shows errors such as:
TypeError: Cannot set property x of #<Object> which has only a getter

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only